### ISSUE TITLE
`statistics_of_labelled_pixels` is missing in API

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#145]
... and it would be great to have it.

Notebook to play with:
https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/22_feature_extraction/statistics_with_pyclesperanto.html

**Comment by StRigaud** [comment]
next update

**Comment by StRigaud** [comment]
Heads-up this one is tricky in a sense that I cannot do all on the C++ side. Mainly because the Python API will expect a dictionnary while other languages will expect different data structure.

The design I have is to enable several independant features computation function like area, etc. And have a statistic function specific per API which follows each language specificity.
