### ISSUE TITLE
Reduce number of bia-bob suggestions

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#245]
The number of functions tagged with "bia-bob-suggestion" is higher than for the _prototype. I reduced the number of suggestions in the _prototype at some point, because the lenght of this list as impact or bia-bob's response time and costs. 

I would like to reduce the list of suggestions. Where do I need to do this @StRigaud ? Is it here, or somewhere in CLIc?

Just for completeness, the prototype currently suggests those functions and we should maybe stick to this list:
```
['binary_edge_detection',
 'binary_not',
 'centroids_of_labels',
 'close_index_gaps_in_label_map',
 'closing_sphere',
 'combine_labels',
 'connected_components_labeling_box',
 'detect_label_edges',
 'difference_of_gaussian',
 'dilate_labels',
 'exclude_labels_on_edges',
 'exclude_large_labels',
 'exclude_small_labels',
 'extend_labels_with_maximum_radius',
 'gaussian_blur',
 'label',
 'label_centroids_to_pointlist',
 'logical_not',
 'map_array',
 'maximum_sphere',
 'maximum_z_projection',
 'mean_sphere',
 'mean_z_projection',
 'merge_touching_labels',
 'minimum_sphere',
 'minimum_z_projection',
 'mode_sphere',
 'read_intensities_from_map',
 'reduce_labels_to_centroids',
 'reduce_labels_to_label_edges',
 'relabel_sequential',
 'replace_intensities',
 'smooth_labels',
 'sobel',
 'statistics_of_labelled_pixels',
 'subtract_gaussian_background',
 'subtract_labels',
 'sum_z_projection',
 'threshold_otsu',
 'top_hat_sphere',
 'voronoi_labeling',
 'voronoi_otsu_labeling']
```

**Comment by haesleinhuepf** [comment]
And we should add functions that are new in pyclesperanto (and not available in the protoype) of course!

**Comment by StRigaud** [comment]
From my understanding, the link between the function and bia-bob is done through the `categories`, by adding or not the `bia-bob-suggestion` in the list?

If so, then we can simple remove / add it for the fonction concerned at the C++ level, in the docstring block.

FYI: it is possible, because of the legacy naming, that 2 "similar" function have the bia-bob tag, we may need to choose then which one we push forward for Bob.

Like i said in this issue: clEsperanto/CLIc#344, I am getting lost on the categories, so do not hesitate to update or correct them.

**Comment by StRigaud** [comment]
To be precise, the categories are handle only in the `.hpp` file, in the doxygen block using the `@note` tag, e.g.:
https://github.com/clEsperanto/CLIc/blob/b15cd4f100150b59c8ce144fff51759cd97b877e/clic/include/tier1.hpp#L13-L26

**Comment by haesleinhuepf** [comment]
git-bob is on it 😁

**Comment by StRigaud** [comment]
Looking forward to see that 😃

I hope it only remove the tag not the entire function 😅
