### ISSUE TITLE
Clean up __init__.py

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#63]
We do have some imports in `__init__.py` which should be avoided if possible. E.g. [this line](https://github.com/clEsperanto/pyclesperanto/blob/main/pyclesperanto/__init__.py#L97) leads to `cle.os` being part of our public API:

![image](https://user-images.githubusercontent.com/12660498/227157665-a2097338-ced5-4237-91ee-d317e8247740.png)

We should remove all functions from the public API that are not intended to be there. Candidates:
* `os`
* `dType`
* `buffer`
* `info`

Otherwise, people might start using them ;-)

Hint: You can list all members of `cle` using this code:
```
for k in dir(cle):
    print(k)
```

**Comment by StRigaud** [comment]
We may want to deal with caution here.

The `import os` here is directly related to finding OpenCL for the `pip install pyclesperanto`.

**Comment by haesleinhuepf** [comment]
> Do you know if there is a way to publish on pipy but not make it visible so I can do some deployment test?

No idea. Why not testing with `pip install .` from the repository root?

**Comment by StRigaud** [comment]
Because when pushing a wheel for `pipy` I need to provide the OpenCL ICD Loader with it. 
Normally it should be okay as the import test is passing during the wheel compilation.

The `os` in the `__init__` is basically a way to tell the package to look for this OCL I provide so that it does correctly the link. This is (strong) inspiration of what `pyopencl` is doing. I need to test If it breaks or not before removing it.
